spring.application.name=membership
spring.datasource.url=jdbc:h2:mem:membershipdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
# JWT Secret (In production, load from Vault or environment variables)
jwt.secret=452948404D635166546A576E5A7234753778214125442A472D4B615064536756
jwt.expiration=86400000